### ISSUE TITLE
Use external Solr cores

### ISSUE THREAD

**Issue by joostmeijles** [avivasolutionsnl/sitecore-docker#21]
Currently the Solr core database files are internal to the container. External files would be more convenient for re-using indexes.

**Comment by joostmeijles** [comment]
We could copy the cores after installation, and runtime use the official Solr image:
```
solr:
  image: solr:6.6.2
  mem_limit: 4096m
  platform: linux
  command: -force
  volumes:
    - .\cores\Sitecore_fxm_master_index:/opt/solr/server/solr/Sitecore_fxm_master_index
    - .\cores\Sitecore_fxm_web_index:/opt/solr/server/solr/Sitecore_fxm_web_index
    - .\cores\Sitecore_marketingdefinitions_master:/opt/solr/server/solr/Sitecore_marketingdefinitions_master
    - .\cores\Sitecore_marketing_asset_index_web:/opt/solr/server/solr/Sitecore_marketing_asset_index_web
    - .\cores\Sitecore_marketing_asset_index_master:/opt/solr/server/solr/Sitecore_marketing_asset_index_master
    - .\cores\Sitecore_suggested_test_index:/opt/solr/server/solr/Sitecore_suggested_test_index
    - .\cores\Sitecore_core_index:/opt/solr/server/solr/Sitecore_core_index
    - .\cores\Sitecore_master_index:/opt/solr/server/solr/Sitecore_master_index
    - .\cores\Sitecore_web_index:/opt/solr/server/solr/Sitecore_web_index
    - .\cores\xp0_xdb:/opt/solr/server/solr/xp0_xdb
```
For simplicity I propose to remove TLS for Solr from the current setup (as it is only used for development anyway).
@Jonne do you agree?
